// AUTH
export const REGISTER_INITIATED = 'REGISTER_INITIATED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const LOGIN_INITIATED = 'LOGIN_INITIATED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_USER = 'LOGOUT_USER'

// MOVIES
export const GET_MOVIE_LIST_INITIATED = 'GET_MOVIE_LIST_INITIATED';
export const GET_MOVIE_LIST_SUCCESS = 'GET_MOVIE_LIST_SUCCESS';
export const GET_MOVIE_LIST_FAILED = 'GET_MOVIE_LIST_FAILED';